/* murmur_ffi — the simulation-control-only extern "C" surface (design/05_viz_contract.md §4,
 * roadmap.md Phase 11). Generated by cbindgen from crates/murmur_ffi/src/lib.rs — see that
 * file for full safety-contract documentation on every function (each has a `# Safety`
 * doc comment there that this generated header does not reproduce). Do not edit by hand;
 * regenerate with:
 *   .tooling/cargo-install/bin/cbindgen --config cbindgen.toml --output include/murmur_ffi.h
 * (run from crates/murmur_ffi/), after `cargo build -p murmur_ffi`.
 */


#ifndef MURMUR_FFI_H
#define MURMUR_FFI_H

/* This file is auto-generated by cbindgen. Do not modify by hand. */

#include <stdint.h>
#include <stddef.h>

/**
 * The 8 trait sockets, in the fixed order `Simulation::plugin_names()` returns them —
 * `murmur_plugin_name`'s `socket_index` indexes into this.
 */
#define MURMUR_SOCKET_COUNT 8

#define CMD_ADD_PREDATOR 0

#define CMD_REMOVE_PREDATOR 1

#define CMD_ADD_OBSTACLE 2

#define CMD_REMOVE_OBSTACLE 3

#define CMD_SET_PARAM 4

#define CMD_SET_ENVIRONMENT 5

#define CMD_RESET 6

#define CMD_SET_CHECKPOINT_STRIDE 7

#define CMD_REQUEST_METRIC 8

/**
 * Owns the repr(C)-converted per-checkpoint arrays so pointers handed out by
 * `murmur_checkpoint_buffer_get` stay valid for the buffer's lifetime.
 */
typedef struct MurmurCheckpointBuffer MurmurCheckpointBuffer;

typedef struct MurmurSimulation MurmurSimulation;

typedef struct CKeyValue {
  const char *key;
  double value;
} CKeyValue;

/**
 * The construction-time configuration (design/02_plugins.md §1's registry-resolution shape,
 * flattened for C). Every `*const c_char` here is read and copied during `murmur_create` only
 * — none are retained past that call returning.
 */
typedef struct MurmurConfig {
  const char *mode;
  const char *modifier;
  const char *domain;
  const char *spatial_index;
  const char *neighbor_selection;
  const char *speed_model;
  const char *init;
  const char *noise;
  double cruise_speed;
  double max_force;
  double speed_min_factor;
  uint32_t boid_count;
  double dt;
  double vision_radius;
  const struct CKeyValue *plugin_params;
  uintptr_t plugin_params_len;
  uint64_t init_seed;
  const char *const *step_hooks;
  uintptr_t step_hooks_len;
  uint32_t predator_count;
  /**
   * Extra `BoidColumns` capacity reserved for runtime-spawned boids
   * (`CMD_ADD_PREDATOR`) — `SimConfig::spawn_headroom` (roadmap.md §12, G6). `0` means no
   * live spawning will ever succeed for this simulation, same as omitting it.
   */
  uint32_t spawn_headroom;
} MurmurConfig;

typedef struct CVec3 {
  double x;
  double y;
  double z;
} CVec3;

typedef struct CMetrics {
  double polarisation;
  double nematic_order;
  double opacity_int;
  double opacity_ext;
  double r_max;
  double dispersion;
  double mean_nn;
  double mean_speed;
  double angular_momentum;
  uint32_t count;
  uint64_t step;
} CMetrics;

typedef struct CInterpolationHint {
  double max_displacement;
  uint8_t state_changed;
} CInterpolationHint;

/**
 * design/05_viz_contract.md §2.1's `state`/`speed_mult`/`threat_proximity`/`panic`/
 * `blackening`/`spin` — each `Option<T>` becomes a `has_x: u8` flag plus an always-present
 * `x` field (`0`/`0.0` when `has_x == 0`), the standard fixed-C-struct encoding for an
 * optional value this crate already uses elsewhere (e.g. `CCommand`'s `has_seed`).
 */
typedef struct CBoidSnapshot {
  struct CVec3 position;
  struct CVec3 velocity;
  /**
   * Not a direct cast of `Species` (a data-carrying `#[repr(u16)]` enum isn't guaranteed a
   * simple C-compatible layout) — an explicit, documented encoding instead: `0` = Prey,
   * `1` = Predator, `1000 + tag` = `Custom(tag)`.
   */
  uint16_t species_code;
  double theta;
  uint8_t has_state;
  uint8_t state;
  uint8_t has_speed_mult;
  float speed_mult;
  uint8_t has_threat_proximity;
  float threat_proximity;
  uint8_t has_panic;
  float panic;
  uint8_t has_blackening;
  float blackening;
  uint8_t has_spin;
  float spin;
} CBoidSnapshot;

typedef struct CPredatorSnapshot {
  struct CVec3 position;
  struct CVec3 velocity;
} CPredatorSnapshot;

/**
 * design/05_viz_contract.md §2.2's `Environment` — `murmur_ecology`'s own 8 published fields.
 */
typedef struct CEnvironment {
  uint64_t day;
  double hour;
  double dusk_factor;
  uint8_t is_roosting_time;
  uint8_t is_murmuration_season;
  double coherence_factor;
  double temperature;
  uint8_t predator_active;
} CEnvironment;

/**
 * design/05_viz_contract.md §2.2's `WanderState`.
 */
typedef struct CWanderState {
  struct CVec3 center;
  struct CVec3 heading;
} CWanderState;

/**
 * One of `murmur_ripple`'s `NUM_TRAINS` trains — see `CRippleState`.
 */
typedef struct CRippleTrain {
  struct CVec3 origin;
  double radius;
  double phase;
} CRippleTrain;

/**
 * design/05_viz_contract.md §2.2's `RippleState` — a disclosed reinterpretation
 * (`murmur_ripple`'s own module doc, `murmur_core::RippleSnapshot`'s own doc): the per-train
 * breakdown instead of a single `envelope_sum` scalar, which doesn't fit a per-boid quantity.
 * Always exactly 3 trains when populated (`murmur_ripple`'s own fixed `NUM_TRAINS`) — a fixed
 * C array, not a separate pointer+count pair, since the length is a compile-time constant.
 */
typedef struct CRippleState {
  struct CRippleTrain trains[3];
} CRippleState;

/**
 * design/05_viz_contract.md §2.2's own CSG primitive vocabulary. Not a real C tagged union
 * (this crate's own established "flat struct, unused fields for other variants" convention,
 * same as `CCommand`) — `kind` selects which fields are meaningful: `0` = Sphere
 * (`center`/`radius`), `1` = Box (`center`/`half_extent`), `2` = Cylinder
 * (`center`/`axis`/`radius`/`half_height`).
 */
typedef struct CObstaclePrimitive {
  uint8_t kind;
  struct CVec3 center;
  double radius;
  struct CVec3 half_extent;
  struct CVec3 axis;
  double half_height;
} CObstaclePrimitive;

/**
 * design/05_viz_contract.md §2.2's own flat, parent-indexed obstacle-scene node list —
 * `murmur_core::ObstacleNodeSnapshot`'s own shape. `csg_op`: `0` = Union, `1` = Subtract.
 * `has_parent`/`parent` encode `Option<u32>` the same `has_x`/`x` way every other optional
 * field in this crate does.
 */
typedef struct CObstacleNode {
  struct CObstaclePrimitive primitive;
  uint8_t csg_op;
  uint8_t has_parent;
  uint32_t parent;
} CObstacleNode;

/**
 * One checkpoint's data, C-ABI shape (design/05 §2's per-boid/scene-level fields). `boids`/
 * `predators` point into arrays owned by the `MurmurCheckpointBuffer` this came from — valid
 * until `murmur_checkpoint_buffer_destroy` is called on that buffer, not just for this call.
 */
typedef struct CCheckpoint {
  uint64_t session_id;
  uint64_t step_count;
  double sim_time;
  uint64_t base_seed;
  struct CVec3 center_of_mass;
  struct CMetrics metrics;
  struct CInterpolationHint interpolation_hint;
  uint32_t boid_count;
  const struct CBoidSnapshot *boids;
  uint32_t predator_count;
  const struct CPredatorSnapshot *predators;
  uint8_t has_environment;
  struct CEnvironment environment;
  uint8_t has_wander;
  struct CWanderState wander;
  uint8_t has_ripple;
  struct CRippleState ripple;
  uint8_t has_dynamic_vision_range;
  float dynamic_vision_range;
  uint32_t obstacle_count;
  const struct CObstacleNode *obstacles;
} CCheckpoint;

/**
 * A flat, always-fully-sized encoding of `murmur_core::batch::Command` — see module doc
 * "Command encoding." `kind` selects one of the `CMD_*` constants; only the fields that
 * variant actually uses are meaningful.
 */
typedef struct CCommand {
  uint8_t kind;
  struct CVec3 position;
  struct CVec3 velocity;
  uint32_t id;
  /**
   * `SetParam` only — a borrowed, NUL-terminated UTF-8 string, read during the
   * `murmur_run_batch*` call and not retained past it. Null for every other `kind`.
   */
  const char *name;
  double value;
  uint32_t count;
  uint32_t stride;
  uint64_t seed;
  uint8_t has_seed;
} CCommand;

/**
 * Returns the most recent `murmur_create` failure's message on this thread, or null if there
 * hasn't been one (or it wasn't valid UTF-8/contained an interior NUL, which can't happen for
 * error messages we construct ourselves). Valid until the next call to `murmur_create` on
 * this thread.
 */
 const char *murmur_last_error_message(void);

/**
 * # Safety
 * `config` must be null or point to a valid, fully-initialized `MurmurConfig` whose string/
 * array pointers are each valid for the duration of this call (see `MurmurConfig`'s doc).
 * Returns null on any failure — check `murmur_last_error_message()`.
 */
 struct MurmurSimulation *murmur_create(const struct MurmurConfig *config);

/**
 * # Safety
 * `sim` must be either null or a pointer previously returned by `murmur_create` and not yet
 * passed to `murmur_destroy`.
 */
 void murmur_destroy(struct MurmurSimulation *sim);

 uint32_t murmur_plugin_count(void);

/**
 * # Safety
 * `sim` must be a live pointer from `murmur_create`. Returns null if `socket_index` is out of
 * range. The returned pointer is valid until `murmur_destroy(sim)`.
 */
 const char *murmur_plugin_name(const struct MurmurSimulation *sim, uint32_t socket_index);

/**
 * Count of non-fatal construction-time `Warning`s (design/01_core.md §4.1) — e.g. `HashGrid`'s
 * `cell_size` snapped to `vision_radius`. `0` for a composition with nothing to report; never
 * affects whether `murmur_create` returned a live pointer (warnings are advisory, not errors).
 *
 * # Safety
 * `sim` must be a live pointer from `murmur_create`.
 */
 uint32_t murmur_warning_count(const struct MurmurSimulation *sim);

/**
 * One construction-time warning's message, formatted as `"<plugin>: <message>"`. Returns null
 * if `index` is out of range.
 *
 * # Safety
 * `sim` must be a live pointer from `murmur_create`. The returned pointer is valid until
 * `murmur_destroy(sim)`.
 */
 const char *murmur_warning_message(const struct MurmurSimulation *sim, uint32_t index);

/**
 * # Safety
 * `sim` must be a live pointer from `murmur_create`.
 */
 uint64_t murmur_session_id(const struct MurmurSimulation *sim);

/**
 * # Safety
 * `sim` must be a live pointer from `murmur_create`.
 */
 uint64_t murmur_build_hash(const struct MurmurSimulation *sim);

/**
 * # Safety
 * `sim` must be a live pointer from `murmur_create`.
 */
 uint32_t murmur_boid_count(const struct MurmurSimulation *sim);

/**
 * # Safety
 * `sim` must be a live pointer from `murmur_create`.
 */
 uint64_t murmur_step_count(const struct MurmurSimulation *sim);

/**
 * # Safety
 * `sim` must be a live pointer from `murmur_create`. Returns null if `index` is out of range
 * for the error list left by the most recent failed `murmur_run_batch*` call. The pointer is
 * valid until the next `murmur_run_batch*` call on this `sim` or `murmur_destroy(sim)`.
 */
 uintptr_t murmur_last_command_error_count(const struct MurmurSimulation *sim);

/**
 * # Safety
 * See `murmur_last_command_error_count`.
 */
 const char *murmur_last_command_error_message(const struct MurmurSimulation *sim, uintptr_t index);

/**
 * # Safety
 * `buf` must be a live pointer from a `murmur_run_batch*` call, not yet destroyed.
 */
 uintptr_t murmur_checkpoint_buffer_len(const struct MurmurCheckpointBuffer *buf);

/**
 * # Safety
 * `buf` must be a live pointer from a `murmur_run_batch*` call. `index` must be `<
 * murmur_checkpoint_buffer_len(buf)` — out-of-range returns a zeroed `CCheckpoint` with null
 * array pointers rather than reading out of bounds.
 */

struct CCheckpoint murmur_checkpoint_buffer_get(const struct MurmurCheckpointBuffer *buf,
                                                uintptr_t index);

/**
 * # Safety
 * `buf` must be null or a pointer previously returned by a `murmur_run_batch*` call and not
 * yet destroyed. Every `CCheckpoint` obtained from `buf` becomes dangling after this call.
 */
 void murmur_checkpoint_buffer_destroy(struct MurmurCheckpointBuffer *buf);

/**
 * # Safety
 * `sim` must be a live pointer from `murmur_create`. `commands`/`commands_len` per
 * `decode_commands`'s contract. `out_buffer` must be a valid, writable `*mut
 * *mut MurmurCheckpointBuffer`.
 *
 * Returns `0` on success (`*out_buffer` is set to a live buffer the caller must eventually
 * pass to `murmur_checkpoint_buffer_destroy`). Returns `1` if any command failed validation
 * (`*out_buffer` is set to null; the simulation is left completely untouched — no steps ran;
 * inspect `murmur_last_command_error_count`/`_message`). Returns `-1` for a malformed call
 * (null `sim`/`out_buffer`, or an unparseable command array) — check
 * `murmur_last_error_message`.
 */

int32_t murmur_run_batch(struct MurmurSimulation *sim,
                         uint32_t steps,
                         uint64_t base_seed,
                         const struct CCommand *commands,
                         uintptr_t commands_len,
                         struct MurmurCheckpointBuffer **out_buffer);

/**
 * # Safety
 * As `murmur_run_batch`, plus `out_all_done` must be a valid, writable `*mut u8`. On success,
 * `*out_all_done` is `1` if every requested step ran before `time_budget_ms` elapsed, `0` if
 * the batch stopped early (the returned buffer still holds every checkpoint captured before
 * the stop, and `sim`'s state is fully valid — no step is ever left partially applied).
 */

int32_t murmur_run_batch_with_budget(struct MurmurSimulation *sim,
                                     uint32_t steps,
                                     uint64_t base_seed,
                                     const struct CCommand *commands,
                                     uintptr_t commands_len,
                                     double time_budget_ms,
                                     struct MurmurCheckpointBuffer **out_buffer,
                                     uint8_t *out_all_done);

#endif  /* MURMUR_FFI_H */
